### ISSUE TITLE
onos-ric throws exception on Atomix store Get()

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-ric#164]
In the new method `GetUEAdmissionByID()` from #163 I call Get on the Atomix store, but get
a SEGV

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xeed706]

goroutine 140479 [running]:
github.com/onosproject/onos-ric/pkg/store/updates.(*atomixStore).Get(0xc00014bdf0, 0x3, 0xc000cd4810, 0x6, 0xc000cd4816, 0x7, 0xc000cd4840, 0x4, 0x0, 0x0, ...)
	/go/src/github.com/onosproject/onos-ric/pkg/store/updates/store.go:144 +0x2b6
github.com/onosproject/onos-ric/pkg/manager.(*Manager).GetUEAdmissionByID(0x1c79d20, 0xc000b182e0, 0xc000cd4840, 0x4, 0x3, 0xc000e82d40, 0x2)
	/go/src/github.com/onosproject/onos-ric/pkg/manager/manager.go:124 +0xe4
github.com/onosproject/onos-ric/pkg/northbound/c1.Server.ListUELinks(0xc000b88780, 0x13d4380, 0xc00094d5a0, 0xc00006ea01, 0xc00094d5a0)
	/go/src/github.com/onosproject/onos-ric/pkg/northbound/c1/c1.go:187 +0x4fb
github.com/onosproject/onos-ric/api/nb._C1InterfaceService_ListUELinks_Handler(0x1112620, 0x1c97f68, 0x13d0f00, 0xc00096c000, 0x1c97f68, 0xc0010f0200)
	/go/src/github.com/onosproject/onos-ric/api/nb/c1-interface.pb.go:2696 +0x109
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000470600, 0x13d6c00, 0xc0008f7500, 0xc0010f0200, 0xc00045aab0, 0x1c673c0, 0x0, 0x0, 0x0)
	/go/src/github.com/onosproject/onos-ric/vendor/google.golang.org/grpc/server.go:1237 +0xb42
google.golang.org/grpc.(*Server).handleStream(0xc000470600, 0x13d6c00, 0xc0008f7500, 0xc0010f0200, 0x0)
	/go/src/github.com/onosproject/onos-ric/vendor/google.golang.org/grpc/server.go:1317 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000e218e0, 0xc000470600, 0x13d6c00, 0xc0008f7500, 0xc0010f0200)
	/go/src/github.com/onosproject/onos-ric/vendor/google.golang.org/grpc/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/onosproject/onos-ric/vendor/google.golang.org/grpc/server.go:720 +0xa1
```

**Comment by tomikazi** [comment]
Fixed.
